### PR TITLE
Update getting-started.md

### PR DESCRIPTION
**Pull request by auraoupa**
Premier jet à partir de la page d'accueil pour l'équipe MEOM.
Plusieurs questions : 
  - est-ce que l'on recommande toujours conda ? à remplacer par micromamba ?
  - est-ce que l'on parle des ressources de calcul ici ?
  - qu'est-ce qu'il manque ?

### CODE REVIEW

**Comment by lucas-ige** [comment]
Hello, I added 2 commits to the branch:

- one with small cosmetic changes to the original document.
- the other one to recommend using brew on MacOS for basic software management.

**Comment by chekki2mo** [comment]
Hello,
The getting started of the doc is still empty https://ige-calcul.github.io/public-docs/docs/getting-started.html#getting-started
I think you can push your changes there
Reference to conda should be replaced par micromamba https://ige-calcul.github.io/public-docs/docs/clusters/Tools/micromamba.html#mamba

**Review by ekwaly — APPROVED** [review]

**Comment by ekwaly** [comment]
@chekki2mo: The changes to the getting-started.md file will be automatically copied to JupyterBook equivalent page by the CI/CD pipeline after the merge.

This is a case we're going to see many times over: there are two sources of information.
1. The one from Meom group : https://github.com/meom-group/tutos/blob/master/conda.md
2. The one from IGE Calcul group : https://ige-calcul.github.io/public-docs/docs/clusters/Tools/micromamba.html#mamba

In both cases, we're talking about installing a Conda environment, but with the miromamba package manager. So that's fine. But there's still the question of which source to use.

**Review by ekwaly — APPROVED** [review]
Fine with myself - Weird.

**Review by auraoupa — COMMENTED** [review]
I agree that mamba is  better !

**Review by ekwaly — APPROVED** [review]

**Comment by ekwaly** [comment]
So someone, apart from me, has to redo a review to trigger the CI/CD pipeline.

**Comment by auraoupa** [comment]
It cannot be me as I started the pull request ...

**Review by lucas-ige — APPROVED** [review]
Fine by me. We will see if the relative links are handled properly when building the notebook...

**Pull request merged**
